spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/register_personal_documents}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:password}
#  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html
#    check-template-location: true